### ISSUE TITLE
game doesn't open

### ISSUE THREAD

**Issue by Aizoniko** [TobyAdd/GDH#100]
the game does not open, with the error "Geometry Dash stopped working", but in console it says that everything is loaded without any errors, how fix it?

**Comment by thisisignitedoreo** [comment]
try reinstalling gd and reinstalling gdh

**Comment by TobyAdd** [comment]
What's your operating system? Make sure you have installed Geometry Dash version 2.204.

**Comment by Alphaotic** [comment]
fixed it, when you go into steam go into settings, then properties, then installed files, and click verify game file integrity!
