### ISSUE TITLE
When you're looking for a level online, the game crash

### ISSUE THREAD

**Issue by alilovic22** [TobyAdd/GDH#101]
it directly crash when you wanna look for a level on gd

**Comment by Ozzyljd** [comment]
no it dont
but try reinstalling gd

**Comment by TobyAdd** [comment]
Try reinstalling GDH and properly activate the hacks to keep track of game crashes

**Comment by TobyAdd** [comment]
Also make sure you have the latest version of Geometry Dash (2.204)
