### ISSUE TITLE
it keeps saying some of the hacks are broken

### ISSUE THREAD

**Issue by CoralDev0** [TobyAdd/GDH#102]
but I keep reinstalling GDH but nothing works also here are the results.
plus, when it skips the error it doesn't launch GD:
`GDH Build 2.51-alpha
Build date: Jan 22 2024 00:06:47
The content.json file has been successfully parsed
Loading hacks...

Text Bypass
- Pattern: 7c ? 85 c9 7f ? 32 db
- Searching offset by pattern
- Success! (0059F9A7)
- Updating original bytes

Character filter
- Pattern: 75 ? 33 c9 eb ? 8b cf 8d 51 ? 90 8a 01 41 84 c0 75 ? 2b ca 51 6a
- Searching offset by pattern
- Success! (0059F974)
- Updating original bytes

Free Shops
- Pattern: 52 50 e8 ? ? ? ? 56
- Searching offset by pattern
- Success! (006D8223)
- Updating original bytes

- Pattern: 74 ? 57 8b ce e8 ? ? ? ? eb
- Searching offset by pattern
- Success! (00786666)
- Updating original bytes

- Pattern: 7d ? 32 db eb ? 2b 83
- Searching offset by pattern
- Success! (006D8205)
- Updating original bytes

Free Chests
- Pattern: 7e ? b8 ? ? ? ? eb ? e8
- Searching offset by pattern
- Success! (006E811B)
- Updating original bytes

- Pattern: 7e ? b8 ? ? ? ? eb ? 81 f9 ? ? ? ? 7e ? b8 ? ? ? ? eb ? 81 f9 ? ? ? ? 7e ? b8 ? ? ? ? eb ? 81 f9
- Searching offset by pattern
- Success! (006E2E0D)
- Updating original bytes

- Pattern: 7e ? bb ? ? ? ? eb ? 81 fe ? ? ? ? 7e ? bb ? ? ? ? eb ? 81 fe ? ? ? ? 7e ? bb ? ? ? ? eb ? 81 fe
- Searching offset by pattern
- Success! (00866DCE)
- Updating original bytes

- Pattern: 0f 8d ? ? ? ? ff 15
- Searching offset by pattern
- Success! (0086742A)
- Updating original bytes

- Pattern: 0f 8d ? ? ? ? 6a ? 8b f3
- Searching offset by pattern
- Success! (00866E18)
- Updating original bytes

All Shops Bypass
- Pattern: 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 8b cf
- Searching offset by pattern
- Success! (00867156)
- Updating original bytes

- Pattern: 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 68 ? ? ? ? e8 ? ? ? ? 8b c8 e8 ? ? ? ? 84 c0 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 8b cf
- Searching offset by pattern
- Success! (00867132)
- Updating original bytes

- Pattern: 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 68 ? ? ? ? e8 ? ? ? ? 8b c8 e8 ? ? ? ? 84 c0 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 68 ? ? ? ? e8 ? ? ? ? 8b c8 e8 ? ? ? ? 84 c0 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 8b cf
- Searching offset by pattern
- Success! (0086710E)
- Updating original bytes

- Pattern: 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 68 ? ? ? ? e8 ? ? ? ? 8b c8 e8 ? ? ? ? 84 c0 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 68 ? ? ? ? e8 ? ? ? ? 8b c8 e8 ? ? ? ? 84 c0 75 ? 8b ce e8 ? ? ? ? 5f 5e 8b e5 5d c2 ? ? 68
- Searching offset by pattern
- Success! (008670EA)
- Updating original bytes

Vault of Secrets Bypass
- Pattern: 74 ? ff 15 ? ? ? ? 8b f0 ff 15 ? ? ? ? 89 b0 ? ? ? ? e8 ? ? ? ? 8b 16 8b ce 50 ff 92 ? ? ? ? 56 51 c7 04 24 ? ? ? ? ff 15 ? ? ? ? 83 c4 ? 50 ff 15 ? ? ? ? 8b c8 ff 15 ? ? ? ? e9 ? ? ? ? 6a ? 68 ? ? ? ? 8d 4c 24 ? c7 44 24 ? ? ? ? ? c7 44 24 ? ? ? ? ? c6 44 24 ? ? e8 ? ? ? ? c7 44 24
- Searching offset by pattern
- Success! (005E0991)
- Updating original bytes

- Pattern: 74 ? ff 15 ? ? ? ? 8b f0 ff 15 ? ? ? ? 89 b0 ? ? ? ? e8 ? ? ? ? 8b 16 8b ce 50 ff 92 ? ? ? ? 56 51 c7 04 24 ? ? ? ? ff 15 ? ? ? ? 83 c4 ? 50 ff 15 ? ? ? ? 8b c8 ff 15 ? ? ? ? e9 ? ? ? ? 6a ? 68 ? ? ? ? 8d 4c 24 ? c7 44 24 ? ? ? ? ? c7 44 24 ? ? ? ? ? c6 44 24 ? ? e8 ? ? ? ? c7 84 24
- Searching offset by pattern
- Success! (0086F97C)
- Updating original bytes

- Pattern: 0f 9d ? 84 c9
- Searching offset by pattern
- Success! (005DF9EB)
- Updating original bytes

Vault of Secrets Key Bypass
- No pattern, skipping...

- No pattern, skipping...

- No pattern, skipping...

The Treasure Room Bypass
- Pattern: 74 ? ff 15 ? ? ? ? 8b f0 ff 15 ? ? ? ? 32 c9
- Searching offset by pattern
- Success! (005E0CB5)
- Updating original bytes

NoClip
- Pattern: 74 ? 8b 8b ? ? ? ? 85 c9 74 ? 8b 80
- Searching offset by pattern
- Success! (00850AF0)
- Updating original bytes

Unlock All Icons
- Pattern: 8b d9 8b 7d ? 8b 75 ? 85 ff
- Searching offset by pattern
- Success! (0069019B)
- Updating original bytes

- Pattern: 8b d9 8b 75 ? 8b 7d
- Searching offset by pattern
- Success! (0069069B)
- Updating original bytes

Unlock All Levels
- Pattern: 7e ? 2b c7 50
- Searching offset by pattern
Pattern not found (Hack can be broken)

No Transition
- Pattern: F3 ? ? ? ? 68 ? ? ? ? FF
- Searching offset by pattern
- Success! (62CA7414)
- Updating original bytes

No Respawn Flash
- Pattern: 0f 85 ? ? ? ? 56 6a
- Searching offset by pattern
- Success! (0083BD5A)
- Updating original bytes

No Death Effect
- Pattern: e8 ? ? ? ? 5f 5e 59 5d c2 ? ? 8b 86
- Searching offset by pattern
- Success! (0083C3B2)
- Updating original bytes

No Wave Pulse
- Pattern: C1 8B ? ? ? ? ? F3 0F 11 80 ? ? ? ? 8B
- Searching offset by pattern
- Success! (0084D37B)
- Updating original bytes

No Particles
- Pattern: 0F 84 ? ? ? ? 83 BE ? ? ? ? ? 0F
- Searching offset by pattern
- Success! (62CBD24A)
- Updating original bytes

Trail Always Off
- Pattern: 0F 84 ? ? ? ? 85 C0
- Searching offset by pattern
- Success! (62CB0E4C)
- Updating original bytes

Trail Always On
- Pattern: 0F 84 ? ? ? ? 85 C0
- Searching offset by pattern
- Success! (62CB0E4C)
- Updating original bytes

Inversed Trail
- Pattern: 0F 84 ? ? ? ? 85 C0
- Searching offset by pattern
- Success! (62CB0E4C)
- Updating original bytes

Forever Trail
- Pattern: C1 F3 ? 59 0D
- Searching offset by pattern
- Success! (62CB0A00)
- Updating original bytes

- Pattern: 00 C3 CC CC CC CC CC CC CC CC 55 8B EC 56
- Searching offset by pattern
- Success! (62CB0C16)
- Updating original bytes

Solid Wave Trail
- Pattern: 75 ? 80 BE A2
- Searching offset by pattern
- Success! (0082EB61)
- Updating original bytes

- Pattern: 75 ? 8b 86 ? ? ? ? c6 80 ? ? ? ? ? eb
- Searching offset by pattern
- Success! (0082EB6A)
- Updating original bytes

Fast Chest Open
- Pattern: c7 04 24 ? ? ? ? ff 15 ? ? ? ? 8b 3d ? ? ? ? c7 04 24
- Searching offset by pattern
- Success! (00860F2D)
- Updating original bytes

Pause During Complete
- Pattern: 80 bf ? ? ? ? ? 0f 85 ? ? ? ? 80 bf ? ? ? ? ? 0f 85 ? ? ? ? ff 15
- Searching offset by pattern
- Success! (00854FD8)
- Updating original bytes

User-Coins In Practice
- Pattern: 0f 85 ? ? ? ? 8b 8f ? ? ? ? 6a ? ff b6
- Searching offset by pattern
- Success! (00708CEC)
- Updating original bytes

Ignore ESC
- Pattern: E8 ? ? ? ? 83 EC ? 8B CC 89 65 F0 6A
- Searching offset by pattern
- Success! (00824F31)
- Updating original bytes

No Camera Move
- Pattern: 55 8b ec 83 e4 ? 83 ec ? 56 8b f1 8b 86 ? ? ? ? 3d
- Searching offset by pattern
- Success! (0091BFB0)
- Updating original bytes

No Camera Zoom
- Pattern: FF B7 ? ? ? ? F3 0F 10 87 ? ? ? ? FF B7 ? ? ? ? F3
- Searching offset by pattern
- Success! (00906FC4)
- Updating original bytes

No Shaders
- Pattern: 0F 8B ? ? ? ? 8B 8E ? ? ? ? ? ? ? ? ? ? ? ? C6
- Searching offset by pattern
- Success! (008EC34D)
- Updating original bytes

- Pattern: ff 15 ? ? ? ? 8b 8f ? ? ? ? 8b 01 ff 90 ? ? ? ? 8b c8 ff 15 ? ? ? ? 83 ec
- Searching offset by pattern
- Success! (008EC521)
- Updating original bytes

Trail Cutting
- Pattern: F3 0F 59 C2 E8
- Searching offset by pattern
- Success! (62CB0A2F)
- Updating original bytes

All Modes Platformer
- Pattern: 0f 85 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 84 c0 0f 84 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 6a ? 51 56 53 8b cf e8 ? ? ? ? e9 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 84 c0 0f 84 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 51 56 53 8b cf e8 ? ? ? ? e9 ? ? ? ? 80 bf
- Searching offset by pattern
- Success! (00708837)
- Updating original bytes

- Pattern: 0f 85 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 84 c0 0f 84 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 6a ? 51 56 53 8b cf e8 ? ? ? ? e9 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 84 c0 0f 84 ? ? ? ? 56 53 8b cf e8 ? ? ? ? 51 56 53 8b cf e8 ? ? ? ? e9 ? ? ? ? 56
- Searching offset by pattern
- Success! (00708898)
- Updating original bytes

Force Platformer
- Pattern: 8a 90 ? ? ? ? 8b 87
- Searching offset by pattern
- Success! (00729639)
- Updating original bytes

- Pattern: 74 ? 8b 87 ? ? ? ? c7 80 ? ? ? ? ? ? ? ? 8b 87 ? ? ? ? 80 b8
- Searching offset by pattern
- Success! (0072966A)
- Updating original bytes

No Short Numbers
- Pattern: 7d ? 56 8d 8d
- Searching offset by pattern
- Success! (005B51BE)
- Updating original bytes

No Wave Trail
- Pattern: 80 be ? ? ? ? ? 74 ? 8b 06 8b ce ff 50 ? 50
- Searching offset by pattern
- Success! (00842F40)
- Updating original bytes

Safe Mode
- Pattern: 80 bb ? ? ? ? ? 0f 85 ? ? ? ? 80 bb ? ? ? ? ? 0f 85 ? ? ? ? 8a 8b
- Searching offset by pattern
- Success! (00850CDF)
- Updating original bytes

- Pattern: 80 bb ? ? ? ? ? 0f 85 ? ? ? ? 80 bb ? ? ? ? ? 0f 85 ? ? ? ? 8b 8b
- Searching offset by pattern
- Success! (008480D1)
- Updating original bytes

- Pattern: 80 bb ? ? ? ? ? 0f 85 ? ? ? ? 8d 44 24
- Searching offset by pattern
- Success! (008482D6)
- Updating original bytes

Music Unlocker
- Pattern: 75 ? 8b ce e8 ? ? ? ? 5e c2 ? ? 83 be ? ? ? ? ? 7e ? e8 ? ? ? ? 8b b6 ? ? ? ? 39 b0 ? ? ? ? 75 ? e8 ? ? ? ? c7 80 ? ? ? ? ? ? ? ? e8
- Searching offset by pattern
- Success! (008F5293)
- Updating original bytes

- Pattern: 75 ? 8b ce e8 ? ? ? ? 5e c2 ? ? 83 be ? ? ? ? ? 7e ? e8 ? ? ? ? 8b b6 ? ? ? ? 39 b0 ? ? ? ? 75 ? e8 ? ? ? ? c7 80 ? ? ? ? ? ? ? ? 5e
- Searching offset by pattern
- Success! (008F5313)
- Updating original bytes

- Pattern: 0f 85 ? ? ? ? 8b ce 8b 35
- Searching offset by pattern
- Success! (008F4D94)
- Updating original bytes

Force Visibility
- Pattern: 8a 45 ? 88 81 ? ? ? ? 5d c2 ? ? 55 8b ec 56 ff 75
- Searching offset by pattern
- Success! (62C615C3)
- Updating original bytes

- Pattern: 0f 84 ? ? ? ? e8 ? ? ? ? 8b 8b
- Searching offset by pattern
- Success! (62C61B6A)
- Updating original bytes

Free Window Resize
- Pattern: e8 ? ? ? ? 83 c4 ? e9 ? ? ? ? c6 87
- Searching offset by pattern
- Success! (62D1848B)
- Updating original bytes

Allow Low Volume
- Pattern: 76 ? 0F 57 C0 F3 ? ? ? ? E8
- Searching offset by pattern
- Success! (0081C040)
- Updating original bytes

- Pattern: 76 ? 0F 57 C0 F3 ? ? ? ? E8 ? ? ? ? F3 ? ? ? ? 51
- Searching offset by pattern
- Success! (0081C131)
- Updating original bytes

No Glow
- Pattern: 74 ? c6 44 24 ? ? e8
- Searching offset by pattern
- Success! (00846B3D)
- Updating original bytes

- Pattern: 0f 84 ? ? ? ? 80 7d ? ? 74 ? c6 80 ? ? ? ? ? 83 ec ? 8b cc 68 ? ? ? ? e8 ? ? ? ? 8d 44 24 ? 50 e8 ? ? ? ? c7 44 24 ? ? ? ? ? 83 78 ? ? 72 ? 8b 00 50 ff 15 ? ? ? ? 83 c4 ? c7 44 24 ? ? ? ? ? 83 7c 24 ? ? 8b f0 72 ? ff 74 24 ? ff 15 ? ? ? ? 83 c4 ? c7 44 24 ? ? ? ? ? c7 44 24 ? ? ? ? ? c6 44 24 ? ? 8b 06 51 8b ce c7 04 24 ? ? ? ? ff 90 ? ? ? ? 8b 8f ? ? ? ? 56 8b 01 ff 90 ? ? ? ? 8b 8f ? ? ? ? 8d 44 24 ? 68 ? ? ? ? 50 ff 15 ? ? ? ? 8b 06 8d 4c 24 ? 51 8b ce ff 50 ? 8b 4c 24 ? 64 89 0d ? ? ? ? 59 5f 5e 8b 4c 24 ? 33 cc e8 ? ? ? ? 8b e5 5d c2 ? ? cc cc cc cc cc 55
- Searching offset by pattern
- Success! (006B1960)
- Updating original bytes

- Pattern: 0f 84 ? ? ? ? 80 7d ? ? 74 ? c6 80 ? ? ? ? ? 83 ec ? 8b cc 68 ? ? ? ? e8 ? ? ? ? 8d 44 24 ? 50 e8 ? ? ? ? c7 44 24 ? ? ? ? ? 83 78 ? ? 72 ? 8b 00 50 ff 15 ? ? ? ? 83 c4 ? c7 44 24 ? ? ? ? ? 83 7c 24 ? ? 8b f0 72 ? ff 74 24 ? ff 15 ? ? ? ? 83 c4 ? c7 44 24 ? ? ? ? ? c7 44 24 ? ? ? ? ? c6 44 24 ? ? 8b 06 51 8b ce c7 04 24 ? ? ? ? ff 90 ? ? ? ? 8b 8f ? ? ? ? 56 8b 01 ff 90 ? ? ? ? 8b 8f ? ? ? ? 8d 44 24 ? 68 ? ? ? ? 50 ff 15 ? ? ? ? 8b 06 8d 4c 24 ? 51 8b ce ff 50 ? 8b 4c 24 ? 64 89 0d ? ? ? ? 59 5f 5e 8b 4c 24 ? 33 cc e8 ? ? ? ? 8b e5 5d c2 ? ? cc cc cc cc cc 83 b9
- Searching offset by pattern
- Success! (006B1AF0)
- Updating original bytes

Mode Console
- Pattern: 00 75 ? 33 c0 eb ? b8 ? ? ? ? 88 86
- Searching offset by pattern
- Success! (62CC4A54)
- Updating original bytes

No Orb Ring
- Pattern: 83 b8 ? ? ? ? ? 0f 84 ? ? ? ? 80 bf ? ? ? ? ? 0f 85 ? ? ? ? 81 bf
- Searching offset by pattern
- Success! (00903398)
- Updating original bytes

Custom object Bypass
- Pattern: 0f 86 ? ? ? ? 68 ? ? ? ? 68
- Searching offset by pattern
- Success! (006176A4)
- Updating original bytes

- Pattern: 77 ? 83 ec ? 8d 44 24
- Searching offset by pattern
- Success! (00617854)
- Updating original bytes

Copy Hack
- Pattern: 0f 84 ? ? ? ? e8 ? ? ? ? 8b 88 ? ? ? ? 2b 88 ? ? ? ? 74
- Searching offset by pattern
- Success! (007BE077)
- Updating original bytes

Slider Limit
- Pattern: 76 ? 0F 57 C0 84
- Searching offset by pattern
- Success! (005BCDAA)
- Updating original bytes

- Pattern: 76 ? 0F 57 C9
- Searching offset by pattern
- Success! (005BCDD8)
- Updating original bytes

- Pattern: 75 ? 0F 2F CA
- Searching offset by pattern
- Success! (0064E538)
- Updating original bytes

Verify Hack
- Pattern: 74 ? 80 b9 ? ? ? ? ? 75 ? 83 ec
- Searching offset by pattern
- Success! (008F1BF5)
- Updating original bytes

Level Edit
- Pattern: 0f 85 ? ? ? ? 68 ? ? ? ? ff d7
- Searching offset by pattern
Pattern not found (Hack can be broken)

- Pattern: 83 B8 ? ? ? ? ? 0F 44 CA 51 56
- Searching offset by pattern
Pattern not found (Hack can be broken)

- Pattern: 0f 85 ? ? ? ? ff 15 ? ? ? ? 8b c8 8b 10 ff 52 ? c7 40
- Searching offset by pattern
Pattern not found (Hack can be broken)

- Pattern: 8a c3 5b 5d c3 8d 49
- Searching offset by pattern
- Success! (007E0AC4)
- Updating original bytes

success: 72; skip: 3, fail: 4; loaded and updated opcodes
MinHook successfully initialized
Successfully enabled all hooks
`

**Comment by TobyAdd** [comment]
It would be better if you uploaded the log to a txt file, but the problem may be that you do not have the latest version of Geometry Dash installed (2.204)
