### ISSUE TITLE
AM I dumb or does the replay engine suck more than I do

### ISSUE THREAD

**Issue by soda69** [TobyAdd/GDH#103]
The replay engine randomly dies? Idk what the right settings should be but my FPS is 200 in game (vsync) and my FPS multiplier is at 200 (real time), but every time I finish a replay and save it, then load it after playing in practice mode, the replay will die at random spots. Is it supposed to be like that or am i dumb and i'm not supposed to record a replay in practice mode when i die

**Comment by Sapphire-code** [comment]
I've also noticed this issue. My guess is that the points you die at in practice mode will be the same points you die at while the macro is running. 

The only thing that fixed it for me was to use the **speed hack**, then play in **normal mode**.

**Comment by Sapphire-code** [comment]
> The replay engine randomly dies? Idk what the right settings should be but my FPS is 200 in game (vsync) and my FPS multiplier is at 200 (real time), but every time I finish a replay and save it, then load it after playing in practice mode, the replay will die at random spots. Is it supposed to be like that or am i dumb and i'm not supposed to record a replay in practice mode when i die

I've also noticed this issue. My guess is that the points you die at in practice mode will be the same points you die at while the macro is running.

The only thing that fixed it for me was to use the speed hack, then play in normal mode.

**Comment by soda69** [comment]
> > The replay engine randomly dies? Idk what the right settings should be but my FPS is 200 in game (vsync) and my FPS multiplier is at 200 (real time), but every time I finish a replay and save it, then load it after playing in practice mode, the replay will die at random spots. Is it supposed to be like that or am i dumb and i'm not supposed to record a replay in practice mode when i die
> 
> I've also noticed this issue. My guess is that the points you die at in practice mode will be the same points you die at while the macro is running.
> 
> The only thing that fixed it for me was to use the speed hack, then play in normal mode.

Turns out the replay works with practice mode even if you die, it just seems to lose timing or something. Even without dying and only speed hack, the bot will click too late or too early and die.

**Comment by Sapphire-code** [comment]
> > > The replay engine randomly dies? Idk what the right settings should be but my FPS is 200 in game (vsync) and my FPS multiplier is at 200 (real time), but every time I finish a replay and save it, then load it after playing in practice mode, the replay will die at random spots. Is it supposed to be like that or am i dumb and i'm not supposed to record a replay in practice mode when i die
> > 
> > 
> > I've also noticed this issue. My guess is that the points you die at in practice mode will be the same points you die at while the macro is running.
> > The only thing that fixed it for me was to use the speed hack, then play in normal mode.
> 
> Turns out the replay works with practice mode even if you die, it just seems to lose timing or something. Even without dying and only speed hack, the bot will click too late or too early and die.

Yes, you are indeed correct, I just noticed this issue as soon as I commented on your post. I hope the devs can see this and get it fixed soon.

**Comment by TobyAdd** [comment]
Make sure that FPS Multiplier is enabled and GD's fps unlocker and vertical sync are disabled.

**Comment by soda69** [comment]
> Make sure that FPS Multiplier is enabled and GD's fps unlocker and vertical sync are disabled.

I have confirmed both, but it's still not working on 200 FPS.

**Comment by Sapphire-code** [comment]
> Make sure that FPS Multiplier is enabled and GD's fps unlocker and vertical sync are disabled.

Sadly, GD simply **breaks** if I **disable V-Sync**, due to the game constantly **screen tearing** and levels becoming **unplayable**. This is nothing to do with the hack itself, but the main game and my device.

If you could kindly **suggest** a work-around, it would be really helpful.

**Comment by Sapphire-code** [comment]
> > Make sure that FPS Multiplier is enabled and GD's fps unlocker and vertical sync are disabled.
> 
> Sadly, GD simply **breaks** if I **disable V-Sync**, due to the game constantly **screen tearing** and levels becoming **unplayable**. This is nothing to do with the hack itself, but the main game and my device.
> 
> If you could kindly **suggest** a work-around, it would be really helpful.

Edit: Managed to get GD working without V-sync, and it's still broken. :(, talking about version 2.41 of GDH.

**Comment by TobyAdd** [comment]
The bug with replay engine is really exist, and it happens very strange, as recording on some computers works fine, and on some macros can break, I will possibly rewrite the replay system to try to fix it.

**Comment by Sapphire-code** [comment]
> The bug with replay engine is really exist, and it happens very strange, as recording on some computers works fine, and on some macros can break, I will possibly rewrite the replay system to try to fix it.

Thanks a ton! Hope this gets fixed soon, btw if possible could you make this mod menu backwards compatible? As I sadly cannot upgrade my game version due to limitations and am stuck on v2.200

**Comment by KotomanOrNot** [comment]
All gd bots except ybot have this issue to avoid it you have to just not buffer before respawning

**Comment by TobyAdd** [comment]
Replay Engine in GDH 3.0 would be much better about accuracy
