### ISSUE TITLE
FPS Multiplier doesn't save Values, resets to 60

### ISSUE THREAD

**Issue by charuse** [TobyAdd/GDH#104]
FPS Multiplier resets itself to 60 on every new game launch, regardless of if I set it to a different FPS. All the other options save correctly when relaunching GD.

Version 2.51

**Comment by TobyAdd** [comment]
This is indeed a flaw on the part of autosave that does not save the FPS value, it will be fixed in the next version of GDH.

**Comment by TobyAdd** [comment]
Fixed
