### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by ghost** [TobyAdd/GDH#11]
is this safe bro

**Comment by darik9pl** [comment]
and how to use it?

**Comment by darik9pl** [comment]
bruh downloader.bat doesnt work for me
![Zrzut ekranu 2023-05-19 203507](https://github.com/TobyAdd/GDH/assets/114980083/3babe0d1-0d38-4277-8e8e-b25eef1c72f5)

**Comment by zaphir-code** [comment]
some error in download.bat prob cuz code is working properly

**Comment by darik9pl** [comment]
ok

**Comment by strainxx** [comment]
2 iq?

**Comment by darik9pl** [comment]
> 2 iq?

uh... no

**Comment by OMEGA6405** [comment]
@darik9pl yes its safe and to run it you just move all the files to gd file directory. if you need more help just notify me.

**Comment by darik9pl** [comment]
> @darik9pl yes its safe and to run it you just move all the files to gd file directory. if you need more help just notify me.

thanks

**Comment by OMEGA6405** [comment]
@darik9pl if it works you should probably close the issue
