### ISSUE TITLE
Not really an issue but a few suggestions

### ISSUE THREAD

**Issue by gaminggunster** [TobyAdd/GDH#110]
Add an uncompleter?
I have tons of hacked levels from when i was an idiot kid, and really want them off my completed demons.
Try to uncap the FPS multiplier, I know you've put a cap on it for a reason, but sometimes when botting levels, even at max fps, its a little laggy. Not exactly laggy, but its not smooth.

**Comment by TobyAdd** [comment]
Will try to add level uncompleter. About fps multiplier, its not like fps bypass, fps multiplier multiple frames to process more frames for the level (depending on fps), at the same time, it blocks the delta to make the macro more accurate since the delta can be random and the macro can get broken.

**Comment by gaminggunster** [comment]
> Will try to add level uncompleter. About fps multiplier, its not like fps bypass, fps multiplier multiple frames to process more frames for the level (depending on fps), at the same time, it blocks the delta to make the macro more accurate since the delta can be random and the macro can get broken.

Oh ok, thanks.
