### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by zekk87** [TobyAdd/GDH#122]
---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

GDH Information:
- Version: 2.52-dev
- Build date: Jan 29 2024 16:50:20

Exception Information:
- Exception Code: C0000096 (Unknown Exception Code)
- Exception Flags: 0
- Exception Address: 0036C084 (GeometryDash.exe + 2DC084)
- Number Parameters: 0

Stack Trace:
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GeometryDash.exe + 2DC084
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GeometryDash.exe + 2DBEEC
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GeometryDash.exe + 2DBE5E
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GeometryDash.exe + 26C238
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\libcocos2d.dll + 8847F
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\libcocos2d.dll + 8F014
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\libcocos2d.dll + 910D4
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\libcocos2d.dll + 106CD2
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GDH.dll + 20183
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\libcocos2d.dll + 1029F5
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\libcocos2d.dll + 103143
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GeometryDash.exe + 3C0BE8
- D:\download\Geometry.Dash.v2.203a\Geometry.Dash.v2.203a\Game\GeometryDash.exe + 3C1F8E
- C:\WINDOWS\System32\KERNEL32.DLL + 17BA9
- C:\WINDOWS\SYSTEM32\ntdll.dll + 6BD2B
- C:\WINDOWS\SYSTEM32\ntdll.dll + 6BCAF

Register States:
- EAX: 03C1DBE8
- EBX: 0E39B8D8
- ECX: BE553B47
- EDX: 11113F0F
- ESI: 6F707F94
- EDI: 04529A90
- EBP: 00CFF98C
- ESP: 00CFF984
- EIP: 7768BCAF

---------------------------
OK   
---------------------------

**Comment by TobyAdd** [comment]
You are using outdated Geometry Dash, please use version 2.204
