### ISSUE TITLE
what is this check descirption

### ISSUE THREAD

**Issue by GDMan123** [TobyAdd/GDH#123]
---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

GDH Information:
- Version: 2.52-dev
- Build date: Jan 29 2024 16:50:20

Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 00F86571 (GeometryDash.exe + 176571)
- Number Parameters: 2

Stack Trace:
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 176571
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 1660E4
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 165E57
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 12A17C
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 475A5
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 47043
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 11F787
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 5AD6E
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\libcocos2d.dll + C48FA
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 3BA9B8
- C:\Users\khush\Downloads\Geometry-Dash-2.2-Oficial\Geometry Dash\GeometryDash.exe + 3BBD60
- C:\WINDOWS\System32\KERNEL32.DLL + 200C9
- C:\WINDOWS\SYSTEM32\ntdll.dll + 67B1E
- C:\WINDOWS\SYSTEM32\ntdll.dll + 67AEE

Register States:
- EAX: 050708F8
- EBX: 04DFEDB0
- ECX: FFFFFFEC
- EDX: 00000003
- ESI: 6CFB33C0
- EDI: 0507D960
- EBP: 01AFFADC
- ESP: 01AFFAD4
- EIP: 773B7AEE

---------------------------
OK   
---------------------------

**Comment by TobyAdd** [comment]
Where does the crash occur?

**Comment by TobyAdd** [comment]
Considering that you have a pirated version of Geometry Dash, it is outdated.

**Comment by Prevter** [comment]
> Considering that you have a pirated version of Geometry Dash, it is outdated.

Yeah, it looks like something other than 2.204 to me
