### ISSUE TITLE
Option to Re-Lock chests and undo release monster in vault of secrets? 

### ISSUE THREAD

**Issue by NekoNyanners** [TobyAdd/GDH#125]
So I played around with a couple of options in the menu and e.g. tried to open a couple of chests. 
Now, that hack is obviously only locally, and once I uninstalled the hack, all the chests were locked again...

...except for the last three chests in treasure room (the once you get for unlocking 50, 100 and 200 chests).
Is there a way to re-lock those chests? Since they have been opened without getting the rewards. 

Same goes for the monster in the vault of secrets cellar. I used the hack to free it, and apparently permanently locked myself out of ever opening the Gatekeeper / Chamber of Time. Is there a way to re-lock both of them?

**Comment by TobyAdd** [comment]
Unfortunately not, you need to reset the stats again.

**Comment by NekoNyanners** [comment]
Hey, thanks for the reply. Is it actually technically not possible or is it just not worth adding as a feature? 
Because if there is a way to do it e.g. via cheat engine that would be great too. I'd just need some pointers since I'm not too much into low level. I'd rather not start completely over (and yes, I know its my fault for using cheats on my main...) 

Any help would really be appreciated! And thanks for your amazing work on this!
