### ISSUE TITLE
Geode Support 

### ISSUE THREAD

**Issue by ertup0** [TobyAdd/GDH#129]
Currently, it's not possible to have both Geode and this mod installed at the same time.  Also installing updates from Geode would be much faster.

**Comment by TobyAdd** [comment]
I don't plan to do GDH adaptation for geode, as it would take a lot of opinion and I prefer to develop mods dependently without frameworks.

**Comment by aKingAdam** [comment]
you made the gdh for geode may i ask how do i do that? because i am trying to have gdh and geode at the same time
