### ISSUE TITLE
Practice Music Hack bug when playing from a startpos

### ISSUE THREAD

**Issue by dnchshrp** [TobyAdd/GDH#14]
Steps to represent:
1. Enable Practice Music Hack
2. Open a level that starts from a startpos (example: 69012524)
3. Go to practice mode

Demonstration of the bug(it's hard for me to describe it in words, english is not my native lang):
https://github.com/TobyAdd/GDH/assets/113385003/f2568de0-8c25-4c08-9063-511fa9f0a75e

**Comment by TobyAdd** [comment]
Fixed in 2.41Beta
