### ISSUE TITLE
Installer issue on Linux

### ISSUE THREAD

**Issue by Rustring** [TobyAdd/GDH#140]
Installer can't select GD directory
![Screenshot_20240216_193105](https://github.com/TobyAdd/GDH-Installer/assets/155897302/4d5b2e8a-2a48-4d89-96cb-b60c1210d234)
![Screenshot_20240216_193301](https://github.com/TobyAdd/GDH-Installer/assets/155897302/6779471e-ce3b-4247-8750-3a619f7f6085)

**Comment by TobyAdd** [comment]
GDH Installer not tested on linux. Recommend to install it manually
