### ISSUE TITLE
why cryptominer?

### ISSUE THREAD

**Issue by idk-br9** [TobyAdd/GDH#143]
https://youtu.be/DGLLUSz5l2k

i dont like it when people make money on my computer without my knowledge. If you want money from ur product dont post it on github pls.

**Comment by thisisignitedoreo** [comment]
бро 💀

**Comment by TobyAdd** [comment]
Во-первых: Где вы видите, что в моем Чите есть майнер? То, что Geometry Dash использует мощности видеокарты, не означает, что он использует их именно на майнинг, о котором вы говорите.

Во-вторых: Geometry Dash использует мощности видеокарты для обработки шейдеров и прочих графических эффектов, что требует дополнительных ресурсов видеокарты.

В-третьих:

https://github.com/TobyAdd/GDH/assets/66429886/d1582970-267c-479e-9643-77f8fd227d8d

**Comment by TobyAdd** [comment]
Если вы поймёте сарказм в третьем пункте, то, вероятно, ваш вопрос о "майнере" разрешится.

**Comment by idk-br9** [comment]
> Во-первых: Где вы видите, что в моем Чите есть майнер? То, что Geometry Dash использует мощности видеокарты, не означает, что он использует их именно на майнинг, о котором вы говорите.
> 
> Во-вторых: Geometry Dash использует мощности видеокарты для обработки шейдеров и прочих графических эффектов, что требует дополнительных ресурсов видеокарты.
> 
> В-третьих:
> 2024_02_17_19_35_39_664.mp4

так чел, если этот процесс "обработки шейдеров" прерывается вместе с открытием диспетчера задач то это о чем-то говорит). Да и с условным gdhm такого никогда не бывало

**Comment by idk-br9** [comment]
днем и утром такого не происходит кстати

**Comment by TobyAdd** [comment]
Вы не предоставили ни малейшего доказательства того, что в GDH присутствует майнер. GDH является open source разработкой, в которой включены все исходные коды чита. Вы можете просмотреть его и провести анализ на наличие предполагаемых "майнеров". Если вы доверяете своему разуму больше, чем тем, кто утверждает обратное и не предоставил вам никаких доказательств, то вы можете спокойно удалить GDH.

**Comment by TobyAdd** [comment]
https://github.com/TobyAdd/GDH/assets/66429886/f49ffafc-c29a-4276-9c99-9e16f808bcae

**Comment by DaDoorsDevru** [comment]
Если думаешь что это майнер, то удали и не пользуйся! А не обсирай

**Comment by IzzikRider** [comment]
Приходят два мужика к разработчику:
Первый говорит - ты встроил майнер в GDH!
Разработчик показывает пруфы и говорит - с чего вы взяли что тут майнер?
Мужики дружно говорят - виноват Нейрон!
