### ISSUE TITLE
The game crashes after finishing a level

### ISSUE THREAD

**Issue by NNession** [TobyAdd/GDH#155]
After I finished Electroman Adventures and Deadlocked without Noclip or anything enabled, my game crashes. After opening the game again, it shows I haven't completed the level.

The error I get:
---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

GDH Information:
- Version: 2.52-dev
- Build date: Jan 29 2024 16:50:20

Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 7C4E3570 (libcocos2d.dll + 63570)
- Number Parameters: 2

Stack Trace:
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + 63570
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 1C1A6
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 1B708
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 1B8C1
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 1230FB
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 2DE144
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GDH.dll + 210E6
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + 8F484
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + 91564
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + 106E02
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GDH.dll + 20183
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + 102B05
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\libcocos2d.dll + 103223
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 3C12D8
- C:\Downloads\Geometry.Dash.v2.204a\Geometry.Dash.v2.204a\GeometryDash.exe + 3C267E
- C:\Windows\System32\KERNEL32.DLL + 17BA9
- C:\Windows\SYSTEM32\ntdll.dll + 6BDAB
- C:\Windows\SYSTEM32\ntdll.dll + 6BD2F

Register States:
- EAX: 00000000
- EBX: 00000000
- ECX: 00000000
- EDX: 00000000
- ESI: 00000000
- EDI: 00000000
- EBP: 0113FB30
- ESP: 0113FB28
- EIP: 76FCBD2F

---------------------------
OK   
---------------------------

**Comment by TobyAdd** [comment]
Probably fixed in 3.0
