### ISSUE TITLE
when i try to move the gdh.dll file to the geometry dash folder my microsoft antivirus thing keeps deleteing it because it keeps saying its a severe trojan

### ISSUE THREAD

**Issue by jaquaviousquan** [TobyAdd/GDH#156]
what do i do

**Comment by jaquaviousquan** [comment]
the libextensions.dll and libextensions.dll.bak are safe but the gdh.dll is not according to the antivirus and i only have the libextensions.dll and libextensions.dll.bak in the folder

**Comment by TobyAdd** [comment]
google about disabling your antivirus, software that modifies geometry dash is always detected as a trojan because it modifies the game itself which is suspicious for an antivirus
