### ISSUE TITLE
gd not opening

### ISSUE THREAD

**Issue by usernameistoolongmaximum39characters** [TobyAdd/GDH#157]
![image](https://github.com/TobyAdd/GDH/assets/163178026/d9c34538-f89f-467b-b95c-79fa4a869f5c)

what is that?
it says it's not opening correctly, all the dll's are intalled correctly and content file is alright

**Comment by TobyAdd** [comment]
probably you installed gdh incorrectly or geometry dash files are broken, try to reinstall gdh and redownload gdh again
