### ISSUE TITLE
i cant open the menu, did i put the files into an incorrect location? if so, then where do i put the files?

### ISSUE THREAD

**Issue by bombaatomowa123456** [TobyAdd/GDH#16]
HELP PLS IT NO WORK

**Comment by freakazoiddd** [comment]
Extract the folder, then copy or cut the files inside and paste them into your geometry dash files inside of steam, not the ones inside of appdata. It will probably say to replace a file, click yes to replace it. (example of where your geometry dash steam files are) C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash

**Comment by bombaatomowa123456** [comment]
thank

niedz., 24 gru 2023 o 07:23 freakazoiddd ***@***.***>
napisał(a):
