### ISSUE TITLE
Game crashes when opening the editor

### ISSUE THREAD

**Issue by syneriq** [TobyAdd/GDH#161]
Whenever I try to open the editor, the game crashes and returns an error. I already reinstalled the mod and the game and neither has resolved my issue, although when I deleted the mod I was able to open the editor without crashing

---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 6646D3F2 (ig9icd32.dll + 0x4dd3f2)
- Number Parameters: 2

Stack Trace:
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x4dd3f2
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x593cb5
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x529138
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x52d56e
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x591009
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x5910a9
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x4c97f3
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x7ae329
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x8b35ba
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x58fa78
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x5fd763
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x5fea35
- C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0f12908b4ff13ff7\ig9icd32.dll + 0x870af4
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xeea1e
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xd9963
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0x9f8a2
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0x9e7a0
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0x9e6b7
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0xde4b3
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0xde221
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0xa448a
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0x23a74e
- C:\Users\ \Desktop\Geometry Dash\GDH.dll + 0x31c81
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0x239a27
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0x2399a2
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xae203
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xad27d
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xf8df9
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xbe92c
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xc7922
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0xc794e
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0x116cc9
- C:\Users\ \Desktop\Geometry Dash\libcocos2d.dll + 0x118819
- C:\Windows\System32\USER32.dll + 0x4139b
- C:\Windows\System32\USER32.dll + 0x37b3a
- C:\Windows\System32\USER32.dll + 0x372f6
- C:\Windows\System32\USER32.dll + 0x35aeb
- C:\Windows\SYSTEM32\OPENGL32.dll + 0x4696f
- C:\Windows\System32\USER32.dll + 0x4139b
- C:\Windows\System32\USER32.dll + 0x37b3a
- C:\Windows\System32\USER32.dll + 0x36471
- C:\Windows\System32\USER32.dll + 0x35f90
- C:\Users\ \Desktop\Geometry Dash\GDH.dll + 0x580fa
- C:\Users\ \Desktop\Geometry Dash\GDH.dll + 0x58328
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0x3c12d8
- C:\Users\ \Desktop\Geometry Dash\GeometryDash.exe + 0x3c267e
- C:\Windows\System32\KERNEL32.DLL + 0x1fcc9
- C:\Windows\SYSTEM32\ntdll.dll + 0x67c5e
- C:\Windows\SYSTEM32\ntdll.dll + 0x67c2e

Register States:
- EAX: 000000F8
- EBX: 00000000
- ECX: 00000000
- EDX: 059D7A48
- ESI: 000000F8
- EDI: FFFFFFF0
- EBP: 00E3FE28
- ESP: 00E3FE20
- EIP: 77B07C2E

**Comment by TobyAdd** [comment]
What is your GPU? The error occurred by the video driver

**Comment by syneriq** [comment]
nvm i fixed it now, wasn't sure what was causing it but all i did was reinstall the game again
