### ISSUE TITLE
Lists of bugs I have encountered

### ISSUE THREAD

**Issue by Yabitom** [TobyAdd/GDH#162]
The issues I have encountered so far (May vary for other users idk)

**Major bugs**
- Songs fail to download
- Ticked on options doesn't save/resets after closing
- Reopens TOS at every open

**Minor bug**
- Death counter not working (which is understandable considering it's WIP)

**Comment by TobyAdd** [comment]
Thanks for reporting. It's likely that content.json isn't saving under the GDH folder due to rights permissions. Also, try downloading the music without loading the GDH mod. Also, provide more information about the not working death counter.

**Comment by Yabitom** [comment]
> Thanks for reporting. It's likely that content.json isn't saving under the GDH folder due to rights permissions. Also, try downloading the music without loading the GDH mod. Also, provide more information about the not working death counter.

Tried. It seems that GDH v3 Is somehow causing issues with downloading songs. On the death counter however, not really much to say about it, the counter doesn't go up and just stays at 0.

But I feel like I should ask, would this be an easy fix? Are we expecting a GDH v3.1 soon?

**Comment by TobyAdd** [comment]
https://github.com/TobyAdd/GDH/assets/66429886/54b22286-5b88-4767-b4fd-3519b56346fb

Death counter initially worked fine, can you show me how it works for you?

**Comment by Yabitom** [comment]
> Record_2024_03_26_15_55_25_691.mp4 
> Death counter initially worked fine, can you show me how it works for you?

Death counter works now, my apologies. It turns out it was working, just not the way I expected. I thought it would keep count of the deaths in Normal mode without the use of Noclip.

**Comment by TobyAdd** [comment]
Also, please add me as a friend on Discord, as I need more details to understand why autosave isn't working
@tobyadd
