### ISSUE TITLE
I can't open GDH menu when I'm using Geode.

### ISSUE THREAD

**Issue by Patrykowy21** [TobyAdd/GDH#164]

**Comment by alvinlollo** [comment]
GDH is a "mod loader" according to geode, and i'm pretty sure that having 2 mod loaders goes against geode's TOS, and in the end the preloaded mods won't be compatible with the geode based mods

**Comment by heavyutils** [comment]
> GDH is a "mod loader" according to geode, and i'm pretty sure that having 2 mod loaders goes against geode's TOS, and in the end the preloaded mods won't be compatible with the geode based mods

GDH is not a mod loader.

**Comment by TobyAdd** [comment]
Ported to Geode, have fun
