### ISSUE TITLE
Gd wont open

### ISSUE THREAD

**Issue by ikillmyopps** [TobyAdd/GDH#167]
![image](https://github.com/TobyAdd/GDH/assets/156258642/dd4cbd65-43e9-4961-81d1-00c32bdad414)
I tired everything like reinstalling and all of that

**Comment by IzzikRider** [comment]
Operation system?

**Comment by ikillmyopps** [comment]
Windows 10 on wine

**Comment by ikillmyopps** [comment]
yes

**Comment by IzzikRider** [comment]
its dont working on the linux soft for windows soft. Wine = Wine is not emulator
