### ISSUE TITLE
The game wont open

### ISSUE THREAD

**Issue by Ackomir01** [TobyAdd/GDH#171]
I get this message everytime I open the game:
---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 006C6571 (GeometryDash.exe + 0x176571)
- Number Parameters: 2

Stack Trace:
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x176571
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x1660e4
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x165e57
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x12a17c
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x475a5
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x47043
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x11f787
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x5ad6e
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\libcocos2d.dll + 0xc48fa (cocos2d::CCApplication::run + 0x1a)
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x3ba9b8
- C:\Users\feki-\OneDrive\Desktop\aco\geometry-dash-2.2-oficial\Geometry Dash\GeometryDash.exe + 0x3bbd60
- C:\Windows\System32\KERNEL32.DLL + 0x1fcc9 (BaseThreadInitThunk + 0x19)
- C:\Windows\SYSTEM32\ntdll.dll + 0x67c5e (RtlGetAppContainerNamedObjectPath + 0x11e)
- C:\Windows\SYSTEM32\ntdll.dll + 0x67c2e (RtlGetAppContainerNamedObjectPath + 0xee)

Register States:
- EAX: 04AB0DD0
- EBX: 0152ED90
- ECX: FFFFFFEC
- EDX: 00000003
- ESI: 7A4133C0
- EDI: 04ABC878
- EBP: 0115FF6C
- ESP: 0115FF64
- EIP: 77317C2E

**Comment by MeFiddzy** [comment]
instal not the beta

**Comment by TobyAdd** [comment]
Probably outdated issue, use Geode version
