### ISSUE TITLE
Saving videos through FFMPEG doesn't work

### ISSUE THREAD

**Issue by flzpfnove** [TobyAdd/GDH#172]
The title explains everything, I have the latest version of Geometry Dash with the latest version of this mod menu and the latest FFMPEG binaries moved into the same folder as GeometryDash.exe

Nothing seems wrong other than 9 of the patches being skipped ("- No pattern, skipping..."), but when any video is supposed to be saved a message saying "vsem pizda" gets printed to the console (I'm assuming that means there's some kind of error and GDH can't figure out what it is)

**Comment by TobyAdd** [comment]
![ultragif](https://github.com/TobyAdd/GDH/assets/66429886/29ca5c89-e72d-4487-94b2-d4a08a4f8aa4)

**Comment by flzpfnove** [comment]
thanks for pointing that out, issue fixed
