### ISSUE TITLE
How do i get rid of the hacks?

### ISSUE THREAD

**Issue by Dinorampage519** [TobyAdd/GDH#174]

**Comment by Ilyaviznitsa** [comment]
Just delete mod menu

**Comment by DaDoorsDevru** [comment]
reinstall gd

**Comment by Bidombamb** [comment]
> i had the same problem, so i deleted all the files for gd manually by not using steam and in file explorer after that i went to steam to uninstall gd there (even if i already deleted it manually) and redownload it. that's how i removed GDH. and dont worry you dont need to save for your gd account

sorry if i explained it bad

**Comment by TobyAdd** [comment]
use GDH Installer to remove it
