### ISSUE TITLE
Game crashes after dying

### ISSUE THREAD

**Issue by HMPIWD** [TobyAdd/GDH#178]
![image](https://github.com/TobyAdd/GDH/assets/129892725/85f2e391-fdf4-4e6a-938e-5cb801746cbe)

![image](https://github.com/TobyAdd/GDH/assets/129892725/6076d8a0-4758-4d50-88da-e216b7dd01ed)

![image](https://github.com/TobyAdd/GDH/assets/129892725/cda968cc-0c65-4c69-9a2f-5cd67538f86c)

**Comment by TobyAdd** [comment]
Wave Trail Fix is bugged that supposed to crash geometry dash, try to uncheck it and check if you have crashes

**Comment by HMPIWD** [comment]
> Wave Trail Fix is bugged that supposed to crash geometry dash, try to uncheck it and check if you have crashes

Thanks, now it works. Thank you for response, i appreciate it :D
