### ISSUE TITLE
I cant open GD when i install v3.0.

### ISSUE THREAD

**Issue by MeFiddzy** [TobyAdd/GDH#180]
When i install v3.0 cmd pops up and gives me this error message(v2.5 works fine):
---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 01096571 (GeometryDash.exe + 0x176571)
- Number Parameters: 2

Stack Trace:
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x176571
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x1660e4
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x165e57
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x12a17c
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x475a5
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x47043
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x11f787
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x5ad6e
- D:\Apps\Geometry Dash\libcocos2d.dll + 0xc48fa (cocos2d::CCApplication::run + 0x1a)
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x3ba9b8
- D:\Apps\Geometry Dash\GeometryDash.exe + 0x3bbd60
- C:\Windows\System32\KERNEL32.DLL + 0x17ba9 (BaseThreadInitThunk + 0x19)
- C:\Windows\SYSTEM32\ntdll.dll + 0x6be3b (RtlInitializeExceptionChain + 0x6b)
- C:\Windows\SYSTEM32\ntdll.dll + 0x6bdbf (RtlClearBits + 0xbf)

Register States:
- EAX: 04BB92A8
- EBX: 04B40050
- ECX: FFFFFFEC
- EDX: 00000003
- ESI: 72A933C0
- EDI: 04BC1798
- EBP: 00CFFD10
- ESP: 00CFFD08
- EIP: 7792BDBF

---------------------------
OK   
---------------------------

**Comment by TobyAdd** [comment]
Fixed in the latest version
