### ISSUE TITLE
Geometry Dash Crashed (Crash Handler)

### ISSUE THREAD

**Issue by TheDaxMonster** [TobyAdd/GDH#181]
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.

Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 2F2F2F2F (2F2F2F2F)
- Number Parameters: 2

Stack Trace:
- 2F2F2F2F
- D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 0x137c12
- D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 0x13f1de
- D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 0x2e1313
- D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 0x255df5
- D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 0x8f484 (cocos2d::CCActionInterval::step + 0xb4)
- D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 0x91564 (cocos2d::CCActionManager::update + 0x74)
- D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 0x106e02 (cocos2d::CCScheduler::update + 0x52)
- D:\SteamLibrary\steamapps\common\Geometry Dash\GDH.dll + 0x31163 (CCScheduler_update_H + 0xe3 in D:\Source\GDHv3\source\hooks.cpp at line 176)
- D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 0x102b05 (cocos2d::CCDirector::drawScene + 0x25)
- D:\SteamLibrary\steamapps\common\Geometry Dash\libcocos2d.dll + 0x103223 (cocos2d::CCDirector::levelForSceneInStack + 0x83)
- D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 0x3c12d8
- D:\SteamLibrary\steamapps\common\Geometry Dash\GeometryDash.exe + 0x3c267e
- C:\WINDOWS\System32\KERNEL32.DLL + 0x1fcc9 (BaseThreadInitThunk + 0x19)
- C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67c5e (RtlGetAppContainerNamedObjectPath + 0x11e)
- C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67c2e (RtlGetAppContainerNamedObjectPath + 0xee)

Register States:
- EAX: 0000006A
- EBX: 0000003F
- ECX: 1DE375B8
- EDX: 000000D4
- ESI: 007EF0A0
- EDI: 96F3ED95
- EBP: 004FFF00
- ESP: 004FFEF8
- EIP: 77417C2E

---------------------------
OK   
---------------------------

**Comment by TobyAdd** [comment]
fixed in the latest version
