### ISSUE TITLE
Geometry Dash Error

### ISSUE THREAD

**Issue by chaudevsoftware** [TobyAdd/GDH#182]
---------------------------
GeometryDash.exe - Entry Point Not Found
---------------------------
The procedure entry point ?getPreviousPriority@CCLayer@cocos2d@@UAEHXZ could not be located in the dynamic link library D:\Program\Games\Geometry_Dash\GDVH 1.1\Geometry Dash\libExtensions.dll. 
---------------------------
OK   
---------------------------
How can i fix this?

**Comment by TobyAdd** [comment]
Use latest version of Geometry Dash
