### ISSUE TITLE
GDH installer is a virus??

### ISSUE THREAD

**Issue by Bidombamb** [TobyAdd/GDH#183]
im trying to download gdh installer to make gdh suitable with geode, but windows defender says it's a virus. is it true?

it says that the "virus" is serious and its a trojan.

im norwegian so my windows isnt english sadly.

![Bilde_2024-05-21_183655338](https://github.com/TobyAdd/GDH/assets/170450530/5926a1c6-11e8-4943-a4f1-0d56ae967ed6)

pls help me

**Comment by TobyAdd** [comment]
stop creating useless issues

gdh installer have source code, if you don't trust my builds and trust your antivirus, don't use Installer or compile it yourself

**Comment by Rustring** [comment]
Windows Defender is trash anyways
