### ISSUE TITLE
The Cheat Wont open

### ISSUE THREAD

**Issue by rrsyx** [TobyAdd/GDH#188]
Im doing everthing correct but when i press TAB (i also pressed every single key on my keyboard) and of course cheat doesnt open. Please fix this issue

**Comment by Hxrdty** [comment]
i cant even open gd with the cheats in the geometry dash folder

**Comment by hecc124** [comment]
new update on gd, its now 2.206, you cant run stuff for now

**Comment by TobyAdd** [comment]
use latest version of gdh and geometry dash
