### ISSUE TITLE
Fix some hack description (Geode version)

### ISSUE THREAD

**Issue by dejid9** [TobyAdd/GDH#212]
Text Length (now it's same as Checkpoint Limit: "Removes the limit that deletes previous checkpoints after the 50th checkpoint")
Disable Camera Zoom (now it's same as Disable Camera Movement: "Disables camera movement via trigger")

**Comment by TobyAdd** [comment]
thanks, will fix in the next version

**Comment by TobyAdd** [comment]
fixed
