### ISSUE TITLE
The Replay Engine it's doesn't work

### ISSUE THREAD

**Issue by DarkRedInGD** [TobyAdd/GDH#251]
so... why? Replay Engine automaticly disabled when you finished a level in practice mode
and toggle to Play mode, nothing happend, maybe it's Real Time's problem

**Comment by TobyAdd** [comment]
are you have cbf

**Comment by DarkRedInGD** [comment]
ok, i disabled CBF, then Replay Engine works now, thank you

**Comment by LousyBook-01** [comment]
@TobyAdd shouldn't you close this issue?
