### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by misha27317** [TobyAdd/GDH#26]
why when i open game with cheat it's not opening
i press play button on steam a second passes and the game closes
or if i opening game from folder:

почему когда я открываю игру с читом, она не открывается
нажимаю кнопку play в стиме проходит секунда и игра закрывается
или если я открываю игру из папки:
![image](https://github.com/TobyAdd/GDH/assets/126237284/d575e7cc-540d-4c8a-8a09-4fbbbfc13203)
да я русский плят

**Comment by TobyAdd** [comment]
Use GDH Installer to install GDH correctly. https://github.com/TobyAdd/GDH-Installer
