### ISSUE TITLE
Add SHoD and the rotation hitbox no matter what fps are you on

### ISSUE THREAD

**Issue by WhenTheBegininging** [TobyAdd/GDH#289]
so uh, add Show Hitbox on Death.
and add the hitbox for the rotation of the player no matter what fps are you playing so there will be no confusion like "what did i even die to???"

**Comment by TobyAdd** [comment]
![изображение](https://github.com/user-attachments/assets/37b56828-86f2-444d-b1d1-1573a850bf3a)
added
