### ISSUE TITLE
Is this copatible without geode?

### ISSUE THREAD

**Issue by enessmr** [TobyAdd/GDH#296]
My Old GD is unacsessible on Windows, So i have to download a new one. When downloaded, Geode 3.7.6 said The version is too old. (2.2)

**Comment by enessmr** [comment]
Installed 3. version. Fixed

**Comment by enessmr** [comment]
also While making a level:
---------------------------
Geometry Dash Crashed (Crash Handler)
---------------------------
An exception has occurred.
Tip: You can use 'CTRL + C' to copy this message.


Exception Information:
- Exception Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
- Exception Flags: 0
- Exception Address: 6FEB6C62 (libcocos2d.dll + 0xe6c62)
- Number Parameters: 2

Stack Trace:
- C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 0xe6c62
- C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 0x633fe
- C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 0x64081
- C:\Program Files (x86)\Geometry Dash\libcocos2d.dll + 0x6a320
- C:\Program Files (x86)\Geometry Dash\GeometryDash.exe + 0x5b58a
- C:\WINDOWS\System32\USER32.dll + 0x36233
- C:\WINDOWS\System32\USER32.dll + 0x248dd
- C:\WINDOWS\System32\USER32.dll + 0x2404a
- C:\WINDOWS\SYSTEM32\OPENGL32.dll + 0x3f36d
- C:\WINDOWS\System32\USER32.dll + 0x36233
- C:\WINDOWS\System32\USER32.dll + 0x248dd
- C:\WINDOWS\System32\USER32.dll + 0x24380
- C:\WINDOWS\System32\USER32.dll + 0x30bd9
- C:\WINDOWS\SYSTEM32\ntdll.dll + 0x7aa26
- C:\WINDOWS\System32\USER32.dll + 0x36233
- C:\WINDOWS\System32\USER32.dll + 0x234cf
- C:\WINDOWS\System32\USER32.dll + 0x22444
- C:\WINDOWS\System32\USER32.dll + 0x2229e
- C:\WINDOWS\System32\USER32.dll + 0x36233
- C:\WINDOWS\System32\USER32.dll + 0x248dd
- C:\WINDOWS\System32\USER32.dll + 0x24380
- C:\WINDOWS\System32\USER32.dll + 0x30bd9
- C:\WINDOWS\SYSTEM32\ntdll.dll + 0x7aa26
- C:\WINDOWS\System32\USER32.dll + 0x2b8fc
- C:\WINDOWS\System32\USER32.dll + 0x6575c
- C:\WINDOWS\System32\USER32.dll + 0x86393
- C:\WINDOWS\System32\USER32.dll + 0x85122
- C:\WINDOWS\System32\USER32.dll + 0x85c27
- C:\WINDOWS\System32\USER32.dll + 0x85c95
- C:\Program Files (x86)\Geometry Dash\GDH.dll + 0x26f06
- C:\WINDOWS\System32\KERNELBASE.dll + 0x224f02
- C:\WINDOWS\SYSTEM32\ntdll.dll + 0x6bdfd
- C:\WINDOWS\SYSTEM32\ntdll.dll + 0x6bcf1

Register States:
- EAX: 00000000
- EBX: 6FED42B0
- ECX: 00025C00
- EDX: 18656720
- ESI: 18656720
- EDI: 013FC4A8
- EBP: 0118FB80
- ESP: 0118FB78
- EIP: 76FDBCF1


---------------------------
Tamam   
---------------------------

**Comment by TobyAdd** [comment]
GDH v3 has some bugged hacks:
- Wave Trail Fix
- Draw Hitbox trail

try to disable this hacks and after this restart geometry dash
