### ISSUE TITLE
Blinking overlay on AMD GPU's

### ISSUE THREAD

**Issue by gmddurachok** [TobyAdd/GDH#3]
(TobyAdd is know about this bug, I added this issue here to let others know that they are not the only ones with this problem)
На видеокартах AMD интерфейс GDH мерцает. Чтобы это мерцание убрать, нужно отключить вертикальную синхронизацию (V-Sync), но без неё картинка в Geometry Dash становится рваной. Сам TobyAdd говорит, что эта проблема OpenGL. 

https://user-images.githubusercontent.com/99399973/160450042-e8dea447-d047-46cc-96bb-1ea7fe675cff.mp4

**Comment by TobyAdd** [comment]
Я точно не знаю, ли я является это баг OpenGL, но я попытаюсь пофиксить этот баг.

**Comment by OneParsec** [comment]
Странно, несмотря на то что у меня видеокарта от AMD, у меня такого бага нет, вне зависимости включен ли VSync или нет. В любом случае, если человек использует FPS Bypass, ему все равно придётся отключить VSync.

**Comment by TobyAdd** [comment]
fixed

**Comment by mrilyew** [comment]
> fixed

круто
