### ISSUE TITLE
menu wont open

### ISSUE THREAD

**Issue by mrsmellyarmpits** [TobyAdd/GDH#30]
i did all the steps (downloaded release, extracted to steam folder, etc) and nothing happens when i press tab

**Comment by Startive** [comment]
send a picture of your geometry dash folder

**Comment by mrsmellyarmpits** [comment]
![image](https://github.com/TobyAdd/GDH/assets/56747159/ddf9dbd7-e1dd-42d9-b4ea-d4d00c71cc56)

**Comment by Startive** [comment]
hmm, when you load the game, does it give you a runtime error or just an error in general?

**Comment by mrsmellyarmpits** [comment]
no it just doesnt open the menu

**Comment by mrsmellyarmpits** [comment]
if i open it straight from the exe it gives me this
![image](https://github.com/TobyAdd/GDH/assets/56747159/9628b1ad-393d-443d-8c07-95cd93970bd2)

**Comment by CoralDev0** [comment]
> if i open it straight from the exe it gives me this ![image](https://private-user-images.githubusercontent.com/56747159/293111544-9628b1ad-393d-443d-8c07-95cd93970bd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTQ2MDAsIm5iZiI6MTcwNDAxNDMwMCwicGF0aCI6Ii81Njc0NzE1OS8yOTMxMTE1NDQtOTYyOGIxYWQtMzkzZC00NDNkLThjMDctOTVjZDkzOTcwYmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMmVhNjczZGE1N2FkMmYyYjhkM2UwZmY0MWY0ZWIwN2QyZGE4NWJlOTgzNzE4MTg3ZGNkNTQ4ZmY4NWJhZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6qy1ohWkYCd3Ho-Re5NDytUQoiIOr5F9GAzXSlw6HQ)
if you have a geometry dash 2.2 backup use it or use steam to repair it. also download new gdh this error happens cause of the gdh hack has some missing files or entries but when you get a backup and a new gdh it will work also I think you need to install the dependencies.

**Comment by TobyAdd** [comment]
Reinstall Geometry Dash and install GDH again
