### ISSUE TITLE
Bitrate Problem

### ISSUE THREAD

**Issue by MalikHw** [TobyAdd/GDH#302]
When i choose a preset (_happens only on the latest version of GDH_), it does not auto-fill the **bitrate** blank, so i have to manually set it to *50M*, can u fix it, it works perfectly fine before updating GDH

**Comment by TobyAdd** [comment]
In the latest version bitrate is automatically set to 0, that is unlimited bitrate

**Comment by MalikHw** [comment]
so thats fine?
