### ISSUE TITLE
Recorder Presets

### ISSUE THREAD

**Issue by peonii** [TobyAdd/GDH#313]
Upon clicking "8K" 5 times, presets directly taken from OmegaBot 3 pop up. As a developer of OmegaBot, I find this quite flattering, but why exactly does this happen?

**Comment by TobyAdd** [comment]
Presets for FFmpeg are not considered a violation or plagiarism, as they are simply configurations for open-source software and are not protected by copyright.

**Comment by TobyAdd** [comment]
These lines were not created by you but by the developers of FFmpeg, making FFmpeg the original author of this code.

**Comment by peonii** [comment]
I did not once call this plagiarism. I am not filing a copyright complaint. I am simply intrigued by the rather curious naming of the presets, especially since they're hidden behind a "secret" variable.

The FFmpeg creators did not author these lines of code, as it is not code, but rather command line arguments for a program. Neither did you.

I'm mainly saying this as I find you including these presets incredibly funny, especially due to your rather harsh critique of mine and Midget's product.

**Comment by TobyAdd** [comment]
I did not criticize your product in any way, but obviously those filters and adjustments to the arguments that were made by the developers of ffmpeg were not made by you, including me, and they can be used by absolutely any people, so I do not see something funny here.

**Comment by TobyAdd** [comment]
In fact your obot and my recorder is a paste of the replay bot by matcool, lol

**Comment by peonii** [comment]
> In fact your obot and my recorder is a paste of the replay bot by matcool, lol

Untrue, OmegaBot 3's renderer is wildly different from ReplayBot.

**Comment by peonii** [comment]
> I did not criticize your product in any way, but obviously those filters and adjustments to the arguments that were made by the developers of ffmpeg were not made by you, including me, and they can be used by absolutely any people, so I do not see something funny here.

You did, just not in this issue. I don't mind though, there are valid points to be made about OmegaBot.
I just find you hiding the exact ssme (1:1) presets, with matching names, behind some sort of "secret" variable hilarious.

**Comment by TobyAdd** [comment]
> > I did not criticize your product in any way, but obviously those filters and adjustments to the arguments that were made by the developers of ffmpeg were not made by you, including me, and they can be used by absolutely any people, so I do not see something funny here.
> 
> You did, just not in this issue. I don't mind though, there are valid points to be made about OmegaBot. I just find you hiding the exact ssme (1:1) presets, with matching names, behind some sort of "secret" variable hilarious.

Even if I did criticize it, that was a long time ago, back when the drama with the midget was still going on. But I don’t get the nitpicking about the presets. A friend just sent them to me and told me to add them to the Replay Engine Recorder, saying they were pretty good. But the buttons were taking up too much space, so I had to nest them inside another button to show them later.

**Comment by TobyAdd** [comment]
Even if they are from your bot, so what of it?

**Comment by ElPaan** [comment]
> You did, just not in this issue. I don't mind though, there are valid points to be made about OmegaBot. I just find you hiding the exact ssme (1:1) presets, with matching names, behind some sort of "secret" variable hilarious.

Do you actually believe what you’re saying? Did the recorder somehow get worse because of this so-called 'theft'?"

**Comment by peonii** [comment]
> > You did, just not in this issue. I don't mind though, there are valid points to be made about OmegaBot. I just find you hiding the exact ssme (1:1) presets, with matching names, behind some sort of "secret" variable hilarious.
> 
> 
> 
> Do you actually believe what you’re saying? Did the recorder somehow get worse because of this so-called 'theft'?

I don't think you understand basic English; I never said the recorder got worse. Quit whining.

**Comment by peonii** [comment]
> Even if they are from your bot, so what of it?

Nothing! Merely wanted to see how you'd respond.
