### ISSUE TITLE
when i press tab menu wont open

### ISSUE THREAD

**Issue by Frisk4973** [TobyAdd/GDH#33]
self explanatory

**Comment by legoskid** [comment]
send screenshot of game folder

**Comment by geomydas** [comment]
It happened to me aswell.
![image](https://github.com/TobyAdd/GDH/assets/155147963/3e33fc26-4267-49b7-8c52-234631e759c3)
 already extracted all files and opened them using geometry dash. not sure if i did anything wrong though
![image](https://github.com/TobyAdd/GDH/assets/155147963/88ffaccd-4c76-4638-8251-56e3caf683bb)

**Comment by TobyAdd** [comment]
Use GDH Installer to install GDH correctly. https://github.com/TobyAdd/GDH-Installer
