### ISSUE TITLE
is that virus or not?

### ISSUE THREAD

**Issue by Vetka969** [TobyAdd/GDH#34]
![Снимок экрана 2023-12-28 183842](https://github.com/TobyAdd/GDH/assets/111175411/52395298-5d78-4ac1-bb3c-e9ee79e04680)

checked this file on VirusTotal and im find this file " Virus.Patched.OF " is that virus/malware or not ?

**Comment by lilnibblit** [comment]
🥶

**Comment by legoskid** [comment]
No

**Comment by geomydas** [comment]
This is a false positive. Generallly, if some unknown AV flags it as malware or suspicious, it is often a false positive. Also, there are only 2 AV's in your case and it hasn't been detected by some well-known Antivirus, such as Bitdefender or Malwarebyres

**Comment by heavyutils** [comment]
MaxSecure is known for an extreme amount of false positives. Ignore it.

**Comment by H1LOW** [comment]
its safe

**Comment by GEOEGII555** [comment]
> This is a false positive. Generallly, if some unknown AV flags it as malware or suspicious, it is often a false positive. Also, there are only 2 AV's in your case and it hasn't been detected by some well-known Antivirus, such as Bitdefender or Malwarebytes
> Plus, this application is open-source so you be 100% that it isnt malware

Windows Defender also detects it, which isn't an unknown AV. I've already submitted it for review, tho they didn't reply yet.
![Screenshot_2024-03-18-09-20-50-907_org.mozilla.fenix-edit.jpg](https://github.com/TobyAdd/GDH/assets/57674559/98c9f9a3-cf0f-4db6-90af-014ecb84dabf)

**Comment by GEOEGII555** [comment]
> > This is a false positive. Generallly, if some unknown AV flags it as malware or suspicious, it is often a false positive. Also, there are only 2 AV's in your case and it hasn't been detected by some well-known Antivirus, such as Bitdefender or Malwarebytes
> > Plus, this application is open-source so you be 100% that it isnt malware
> 
> Windows Defender also detects it, which isn't an unknown AV. I've already submitted it for review, tho they didn't reply yet. ![Screenshot_2024-03-18-09-20-50-907_org.mozilla.fenix-edit.jpg](https://private-user-images.githubusercontent.com/57674559/313569198-98c9f9a3-cf0f-4db6-90af-014ecb84dabf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTc3ODEsIm5iZiI6MTcxMDg1NzQ4MSwicGF0aCI6Ii81NzY3NDU1OS8zMTM1NjkxOTgtOThjOWY5YTMtY2YwZi00ZGI2LTkwYWYtMDE0ZWNiODRkYWJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE0MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YWE3NjgzNzlmNzcxZTMxOWJlZTYwNjc1MzA2NjQ4NGEwY2I3Y2Q4OGU1YTQyZTljNDM0YTU4ZTk1YjFlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DTagKUKUODiqMJjXncZNtY6UqlX1N5hezs-XUglz25k)
Uhh...
![изображение](https://github.com/TobyAdd/GDH/assets/57674559/bdea6a9b-2aca-4653-a9ae-1795067d79de)
