### ISSUE TITLE
The application was unable to start correctly (0xc0000906)

### ISSUE THREAD

**Issue by GreenWeegeeCantCode** [TobyAdd/GDH#40]
Hi, so yesterday i installed this menu, but now whenever i try to open GD i get this error:

![image](https://github.com/TobyAdd/GDH/assets/145769578/cb449b90-348d-45df-a117-5df92fb0e974)

This never happened before i got the menu, also whenever i start the game and get this error GDH.dll gets deleted for some reason. libExtensions.dll and libExtensions.dll.bak are still in the folder.

**Comment by GreenWeegeeCantCode** [comment]
I literally cant play GD with this menu, i have to play vanilla GD because of this

**Comment by howhathe** [comment]
Hello, disable your anti-virus in system

**Comment by GreenWeegeeCantCode** [comment]
works now
