### ISSUE TITLE
[Question] Auto Collect Coins

### ISSUE THREAD

**Issue by Ghost0Nom** [TobyAdd/GDH#45]
I have a question. Will there be auto collect coins hack in this hack menu?

I asked because I don't want to ram myself into every obstacle, especially those coins which is completely hidden and blend it with the level and only be found once you actually found it.

I hope this hack will be available..

**Comment by westillthinking** [comment]
it would be cool to have this.

what i think would make it even better is if it autocollects the tower coins too.

**Comment by Ion410901** [comment]
Idk how can someone program this hack, but it would be really cool.

**Comment by westillthinking** [comment]
> Idk how can someone program this hack, but it would be really cool.

I mean, absolute did it. its actually pretty easy to do. i think i would have done it if I knew C++.

**Comment by TobyAdd** [comment]
Added in 2.41 Beta
