### ISSUE TITLE
[suggestion] show hitboxes , layout mode, run info and nong song downloader

### ISSUE THREAD

**Issue by MrpootisThePerson** [TobyAdd/GDH#52]
hello tobyadd,

can you please add show hitboxes , layout mode, run info and nong song downloader it will great! for nong song downloader i want it be like this
![image](https://github.com/TobyAdd/GDH/assets/155245387/9144ac31-bd43-4d1f-99bd-f74309bf5085)

**Comment by TobyAdd** [comment]
Will try to make it. Thanks for suggestions
