### ISSUE TITLE
The mod menu GUI has some flickery problems

### ISSUE THREAD

**Issue by Nonoah001** [TobyAdd/GDH#56]
yeah so when i press tab to open the menu

 it flickers but idk why

**Comment by Nonoah001** [comment]
somehow the video didn't upload so here it is : 

https://github.com/TobyAdd/GDH/assets/96695375/03118819-af79-4009-9e2b-ffabd658fa55

**Comment by TobyAdd** [comment]
Disable Vertical Sync

**Comment by Nonoah001** [comment]
I think i found the issue
the fullscreen is making the menu flicker but when i disable it, it doesn't do it

**Comment by Nonoah001** [comment]
wait i accidentally closed it

**Comment by Nonoah001** [comment]
i think the issue is the fullscreen mode since i tried without the fullscreen and it perfectly worked
