### ISSUE TITLE
Opening hacks

### ISSUE THREAD

**Issue by JimmyFlae** [TobyAdd/GDH#98]
I tried every button on my keyboard to open the menu for the hacks but it didn't open. (yes i was tabbed in)

**Comment by Sapphire-code** [comment]
> I tried every button on my keyboard to open the menu for the hacks but it didn't open. (yes i was tabbed in)

Have you pasted all the files in your geometry dash directory?

**Comment by thisisignitedoreo** [comment]
its tab. please read readme before installing stuff

**Comment by Woho2133** [comment]
i tried every button as well including tab and it wont open

**Comment by Sapphire-code** [comment]
> i tried every button as well including tab and it wont open

Did you make sure to **unzip** your folder and **copy** its contents inside your **geometry dash folder**?

**Comment by Woho2133** [comment]
Yes i unzipped and extracted the files into the GD folder where the application is multiple times

**Comment by TobyAdd** [comment]
I recommend installing GDH using the installer, which correctly extracts the GDH archive into Geometry Dash. https://github.com/TobyAdd/GDH-Installer/releases/latest
